### ISSUE TITLE
Unable to login to xxx Application, exiting.

### ISSUE THREAD

**Issue by ghost** [rkadam/automate_atlassian_command_line#1]
Hi,

I tried your ACL tool, unfortunately I receive an error when I try to login to e.g. JIRA. The credentials are correct (copy & paste from 1password) and I tried it with a local user with test as user & password. The error message is 

> Unable to login to JIRA Application, exiting.

Could you tell me what to do?

Regards,
Jan

**Comment by rkadam** [comment]
Jan -- Let me try to reproduce the problem on my side. Will get back to you on this.
